version: '3.8'

services:
  db-blog:
    container_name: db-blog
    image: postgres:17.5
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./migration/:/docker-entrypoint-initdb.d/
    networks:
      - blog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  blog-app:
    container_name: blog-back-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db-blog
      - POSTGRES_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      db-blog:
        condition: service_healthy
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
    name: blog-network

volumes:
  postgres_data:
    name: postgres_data